name: Koniowonsz
author: WodaMuszyna
version: 1.0
main: xyz.wodamuszyna.koniowonsz.Main
api-version: 1.18
commands:
  koniowonsz:
    aliases: [kw]
  lootbox:
  dajlootboxy:
  invsee:
  foreach:
  sethome:
  home:
  rtp:
  checkuser:
  odbierz: